name: CI

on: 
  pull_request:
    branches:
    - v2migration

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
    - name: set AWS and Algolia Keys to environment
      env:
        GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID}}
        GATSBY_ALGOLIA_SEARCH_KEY: ${{secrets.GATSBY_ALGOLIA_SEARCH_KEY}}
        ALGOLIA_ADMIN_KEY: ${{secrets.ALGOLIA_ADMIN_KEY}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        DIST_ID: ${{secrets.DIST_ID}}
      run: npm run build:dev && node_modules/s3-deploy/bin/s3-deploy './public/**' --cwd './public/' --bucket learning.getpostman-beta.com --deleteRemoved --distId E23UCAIQEFBO6 --invalidate '/*'
    - name: lint all markdownfiles
      run: |
        npm install
        node_modules/.bin/markdownlint ./ --ignore node_modules --ignore v5
    - name: check for image url
      run: |
        if grep -lri 's3.amazonaws.com/postman-static-getpostman-com' ./v6 ; 
        then echo "Invalid s3 references found. Please use format 'https://assets.postman.com/postman-docs/[filename-in-s3]'"; 
          exit 1; 
        else echo "no s3 references found"; 
        fi
